# Generated by Django 3.2.9 on 2021-11-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
