# Generated by Django 3.2.9 on 2021-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211107_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Production_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
