# Generated by Django 3.2.9 on 2021-11-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_cast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(to='movies.Cast'),
        ),
    ]
